/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedCrushersRouteImport } from './routes/_authenticated/crushers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDigFacesRouteImport } from './routes/_authenticated/dig-faces'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrushersRoute = AuthenticatedCrushersRouteImport.update({
  id: '/crushers',
  path: '/crushers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDigFacesRoute = AuthenticatedDigFacesRouteImport.update({
  id: '/dig-faces',
  path: '/dig-faces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crushers': typeof AuthenticatedCrushersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dig-faces': typeof AuthenticatedDigFacesRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/production': typeof AuthenticatedProductionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crushers': typeof AuthenticatedCrushersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dig-faces': typeof AuthenticatedDigFacesRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/production': typeof AuthenticatedProductionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/crushers': typeof AuthenticatedCrushersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dig-faces': typeof AuthenticatedDigFacesRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crushers'
    | '/dashboard'
    | '/dig-faces'
    | '/fleet'
    | '/operator'
    | '/production'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crushers'
    | '/dashboard'
    | '/dig-faces'
    | '/fleet'
    | '/operator'
    | '/production'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/crushers'
    | '/_authenticated/dashboard'
    | '/_authenticated/dig-faces'
    | '/_authenticated/fleet'
    | '/_authenticated/operator'
    | '/_authenticated/production'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crushers': {
      id: '/_authenticated/crushers'
      path: '/crushers'
      fullPath: '/crushers'
      preLoaderRoute: typeof AuthenticatedCrushersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dig-faces': {
      id: '/_authenticated/dig-faces'
      path: '/dig-faces'
      fullPath: '/dig-faces'
      preLoaderRoute: typeof AuthenticatedDigFacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrushersRoute: typeof AuthenticatedCrushersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDigFacesRoute: typeof AuthenticatedDigFacesRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrushersRoute: AuthenticatedCrushersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDigFacesRoute: AuthenticatedDigFacesRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
